apiVersion: v1
entries:
  oao-platform:
  - annotations:
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Documentation
          url: https://thfai2000.github.io/open-agent-orchestra/
        - name: Source
          url: https://github.com/thfai2000/open-agent-orchestra
    apiVersion: v2
    appVersion: 1.2.1
    created: "2026-04-13T01:40:22.239807+08:00"
    description: Open Agent Orchestra (OAO) — Autonomous AI workflow engine (API +
      UI + PostgreSQL)
    digest: dacd93b39c7984c0a2ece5cc908008c6850487ee60ba9b2417768d16968018d7
    home: https://github.com/thfai2000/open-agent-orchestra
    keywords:
    - ai
    - agents
    - workflow
    - copilot
    - orchestration
    maintainers:
    - name: thfai2000
      url: https://github.com/thfai2000
    name: oao-platform
    sources:
    - https://github.com/thfai2000/open-agent-orchestra
    type: application
    urls:
    - https://thfai2000.github.io/open-agent-orchestra/charts/oao-platform-1.2.1.tgz
    version: 1.2.1
generated: "2026-04-13T01:40:22.23931+08:00"
