apiVersion: v1
entries:
  oao-platform:
  - annotations:
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Documentation
          url: https://thfai2000.github.io/open-agent-orchestra/
        - name: Source
          url: https://github.com/thfai2000/open-agent-orchestra
    apiVersion: v2
    appVersion: 1.6.0
    created: "2026-04-18T18:20:19.52693782Z"
    description: Open Agent Orchestra (OAO) — Autonomous AI workflow engine (API +
      UI + PostgreSQL)
    digest: 973af040ab1b7b97d754daff08b2df625b7cf76d46208bc14b96c6380f931463
    home: https://github.com/thfai2000/open-agent-orchestra
    keywords:
    - ai
    - agents
    - workflow
    - copilot
    - orchestration
    maintainers:
    - name: thfai2000
      url: https://github.com/thfai2000
    name: oao-platform
    sources:
    - https://github.com/thfai2000/open-agent-orchestra
    type: application
    urls:
    - https://thfai2000.github.io/open-agent-orchestra/charts/oao-platform-1.6.0.tgz
    version: 1.6.0
generated: "2026-04-18T18:20:19.525947658Z"
