apiVersion: apps/v1
kind: Deployment
metadata:
  name: oao-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: oao-ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: oao-ui
  template:
    metadata:
      labels:
        app: oao-ui
    spec:
      containers:
        - name: oao-ui
          image: {{ .Values.ui.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.ui.port }}
          env:
            - name: NUXT_API_BASE_URL
              value: "http://oao-api:{{ .Values.api.port }}"
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: oao-ui
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: oao-ui
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
